### ISSUE TITLE
Fix problem with unreachable resources after build

### ISSUE THREAD

**Issue by marcol13** [marcol13/Java-pong-game#2]
After build project with Maven I have no access to resources from `src/main/resources` which in JAR folder are in the root. 

I get this error after run a game (which successfully open a window, but it don't use any resources: images, fonts, gifs, etc.)

![image](https://github.com/marcol13/Java-pong-game/assets/56632321/4051f37a-8567-45d5-9773-291b21724835)

It should be fixed in order to allow people to play this game in their own computers.

**Comment by tomaszsmy** [comment]
I'm interested to fix issue.

**Comment by marcol13** [comment]
Hi! Of course, you can try to fix that issue! If you succeed, please create a proper Pull Request

**Comment by tomaszsmy** [comment]
#5
